spring:
  r2dbc:
    host: supportdb
    port: 5432
    database: supportservice
    username: supportservice
    password: supportservice123

    url: r2dbc:postgresql://${spring.r2dbc.host}/${spring.r2dbc.database}
  rabbitmq:
      host: rabbit_mq
      port: 5672

  flyway:
    url: jdbc:postgresql://${spring.r2dbc.host}:${spring.r2dbc.port}/${spring.r2dbc.database}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

