# Use postgres/example user/password credentials
version: "3.1"

services:
  factorydb:
    image: mongo
    container_name: factory
    restart: always
 #   ports:
 #   - 27017:27017

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: headquarterservice123
      POSTGRES_USER: headquarterservice
      POSTGRES_DB: headquarterservice

  supportdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: supportservice123
      POSTGRES_USER: supportservice
      POSTGRES_DB: supportservice

  rabbit_mq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/data

  headquarter:
   image: headquarter_service
   restart: always
   build: ./headquarter_service
   ports:
     - 8080:8080
   depends_on: 
     - rabbit_mq
     - db
  
  support-indien:
    image: docker.io/library/support:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8081:8080
    depends_on: 
      - rabbit_mq
      - supportdb
  
  support-mexiko:
    image: docker.io/library/support:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8084:8080
    depends_on: 
      - rabbit_mq
      - supportdb

  factory-usa:
    image: docker.io/library/factory:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8082:8082
    depends_on: 
      - rabbit_mq
      - factorydb 
    environment: 
      - MONGO_URI=mongodb://factorydb:27017/
      - MONGO_DBNAME=factory
      - SERVER_PORT=8082
      - RABBITMQ_HOST=rabbit_mq
      - RABBITMQ_PORT=5672
      - SUPPLIER_HOST=headquarter
      - SUPPLIER_HOST=8080

  factory-china:
    image: docker.io/library/factory:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8083:8083
    depends_on: 
      - rabbit_mq
      - factorydb 
    environment: 
      - MONGO_URI=mongodb://factorydb:27017/
      - MONGO_DBNAME=factory
      - SERVER_PORT=8083
      - RABBITMQ_HOST=rabbit_mq
      - RABBITMQ_PORT=5672
      - SUPPLIER_HOST=headquarter
      - SUPPLIER_HOST=8080
      
volumes:  
  rabbitmq_data: