# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: headquarterservice123
      POSTGRES_USER: headquarterservice
      POSTGRES_DB: headquarterservice

  support_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: supportservice123
      POSTGRES_USER: supportservice
      POSTGRES_DB: supportservice

  rabbit_mq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/data

  headquarter:
   image: headquarter_service
   restart: always
   build: ./headquarter_service
   ports:
     - 8080:8080
   depends_on: 
     - rabbit_mq
     - db
  
  support:
    image: docker.io/library/support:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8081:8080
    depends_on: 
      - rabbit_mq
      - support_db
volumes:  
  rabbitmq_data: