spring:
  main:
    web-application-type: reactive
  rabbitmq:
    host: rabbit_mq
    port: 5672
    #username: msCloudBois
    #password: _420this_is_madness_1337
    #addresses: master.ms.depressive.life:5672
  r2dbc:
    host: db
    port: 5432
    database: centralservice
    username: centralservice
    password: centralservice123
    #url: r2dbc:postgresql://${spring.r2dbc.host}:${spring.r2dbc.port}/${spring.r2dbc.database}
    url: r2dbc:postgresql://${spring.r2dbc.host}/${spring.r2dbc.database}
      
      
  flyway:
    url: jdbc:postgresql://${spring.r2dbc.host}:${spring.r2dbc.port}/${spring.r2dbc.database}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

