spring:
  main:
    web-application-type: reactive
  rabbitmq:
    #host: rabbit_mq
    host: localhost
    port: 5672
    #username: msCloudBois
    #password: _420this_is_madness_1337
    #addresses: master.ms.depressive.life:5672
  r2dbc:
    #host: db
    host: localhost
    port: 5432
    database: headquarterservice
    username: headquarterservice
    password: headquarterservice123
    url: r2dbc:postgresql://${spring.r2dbc.host}:${spring.r2dbc.port}/${spring.r2dbc.database}
    #url: r2dbc:postgresql://${spring.r2dbc.host}/${spring.r2dbc.database}
      
      
  flyway:
    url: jdbc:postgresql://${spring.r2dbc.host}:${spring.r2dbc.port}/${spring.r2dbc.database}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

microservice:
  rabbitmq:
    queue: headquarter.queue
    exchange:   headquarter.exchange
    routingkey: headquarter.routing

