# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: headquarterservice123
      POSTGRES_USER: headquarterservice
      POSTGRES_DB: headquarterservice
    
  #app:
  #  image: headquarter_service
  #  build: .
  #  ports:
  #    - 8080:8080